name: Parse flutter versions

inputs:
  parse-lower-version:
    type: boolean
    default: true
  parse-upper-version:
    type: boolean
    default: true

outputs:
  file-changed: ${{ steps.filter.outputs.file-changed }}
  matrix: ${{ steps.matrix.outputs.matrix }}

runs:
  runs-on: 'composite'
  steps:
    - uses: actions/checkout@v4

    - name: Filter changed files
      uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          file-changed:
            - '**.dart'
            - 'pubspec.yaml'
            - 'pubspec.lock'

    - name: Get Flutter SDK version constraints and packages
      id: matrix
      run: |
        MATRIX_JSON=$(jq -cn --argjson flutter-version "[\"\"]" '$ARGS.named')
        if [ ${{ inputs.parse-lower-version }} ]; then
          MATRIX_JSON=$(echo $MATRIX_JSON | jq --arg flutterVersion flutter-version ".[$flutterVersion] += [\"$(cat pubspec.yaml | yq .environment.flutter | grep -oP '(?<=\>=)[0-9]+\.[0-9]+\.[0-9]+' | head -1)\"]")
        fi

        if [ ${{ inputs.parse-upper-version }} ]; then
          MATRIX_JSON=$(echo $MATRIX_JSON | jq --arg flutterVersion flutter-version ".[$flutterVersion] += [\"$(cat .fvmrc | jq -r .flutter)\"]")
        fi

        echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT
    - name: Print output values
      run: |
        echo "file-changed=${{ steps.filter.outputs.file-changed }}"
        echo "matrix=${{ steps.matrix.outputs.matrix }}"
