name: Generate CHANGELOG
description: Generates CHANGELOG from latest tag to HEAD

inputs:
  package-name:
    required: true

runs:
  using: composite
  steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Move to working directory
        run: cd packages/${{ inputs.package-name }}
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: ../cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md

      - name: Print the changelog
        run: cat "${{ steps.git-cliff.outputs.changelog }}"
