name: Setup
description: Sets up the Flutter environment

inputs:
  flutter-version:
    description: 'The version of Flutter to use'
    required: false
    default: '3.29.0'
  pub-cache:
    description: 'The name of the pub cache variable'
    required: false
    default: package

runs:
  using: composite
  steps:
    - name: 📦 Checkout the repo
      uses: actions/checkout@v4
      with:
        fetch-tags: true
        fetch-depth: 0

    - name: 🚂 Setup Flutter
      uses: arxdeus/flutter-action@main
      with:
        flutter-version: '${{ inputs.flutter-version }}'

    - name: 👷 Install Dependencies
      shell: bash
      run: |
        echo /home/runner/.pub-cache/bin >> $GITHUB_PATH
        flutter config --no-cli-animations --no-analytics
        flutter pub get

