name: Dart Codecheck
description: Checks your Dart Code

inputs:
  dart-version:
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: "Setup Dart ${{ inputs.dart-version }}"
      uses: dart-lang/setup-dart@v1
      with:
        sdk: ${{ inputs.dart-version }}

    - name: "Run tests parallel"
      uses: sambacha/parallelish@v1.0.0
      id: testing-tasks
      with:
          cmd1: find lib test -name "*.dart" ! -name "*.*.dart" -print0 | xargs -0 dart format --set-exit-if-changed --line-length 120
          cmd2: dart analyze --fatal-infos --fatal-warnings
          cmd3: dart --enable-vm-service test --file-reporter="json:${{ github.workspace }}/flutter-test-report.json" --concurrency=6
