name: Parse dart versions

inputs:
  parse-lower-version:
    type: boolean
    default: true
  parse-upper-version:
    type: boolean
    default: true

outputs:
  file-changed:
    value: ${{ steps.filter.outputs.file-changed }}
  matrix:
    value: ${{ steps.matrix.outputs.matrix }}

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - name: Filter changed files
      uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          file-changed:
            - '**.dart'
            - 'pubspec.yaml'
            - 'pubspec.lock'

    - name: Get Dart SDK version constraints and packages
      id: matrix
      shell: bash
      run: |
        MATRIX_JSON=$(jq -cn --argjson dart-version "[\"\"]" '$ARGS.named')
        if [ ${{ inputs.parse-lower-version }} ]; then
          MATRIX_JSON=$(echo $MATRIX_JSON | jq --arg dartVersion dart-version ".[$dartVersion] += [\"$(cat pubspec.yaml | yq .environment.sdk | grep -oP '(?<=\>=)[0-9]+\.[0-9]+\.[0-9]+' | head -1)\"]")
        fi

        if [ ${{ inputs.parse-upper-version }} ]; then
          MATRIX_JSON=$(echo $MATRIX_JSON | jq --arg dartVersion dart-version ".[$dartVersion] += [\"stable\"]")
        fi

        {
          echo 'matrix<<EOF'
          $MATRIX_JSON
          echo EOF
        } >> "$GITHUB_OUTPUT"
    - name: Print output values
      shell: bash
      run: |
        echo "file-changed=${{ steps.filter.outputs.file-changed }}"
        echo "matrix=${{ steps.matrix.outputs.matrix }}"
