name: Publish
permissions:
  contents: write
on:
  workflow_call:
    inputs:
      package-name:
        type: string
        required: true
      package-version:
        type: string
        default: '9.9.9'
        required: true

jobs:
  setup:
      runs-on: ubuntu-latest
      outputs:
        flutter-version: ${{ steps.flutter-version.outputs.version }}
      steps:
        - name: 📦 Get the .github actions
          uses: actions/checkout@v4
          with:
            fetch-tags: true
            fetch-depth: 0
        - name: Get Flutter SDK version
          id: flutter-version
          run: |
            sdk_constraint=$(cat pubspec.yaml | yq .environment.flutter)
            version=$(cat .fvmrc | jq -r .flutter)
            echo "version=$version" >> "$GITHUB_OUTPUT"

  dry_publish:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Codecheck (Flutter ${{ needs.setup.outputs.flutter-version }})
        uses: arxdeus/github_workflows/actions/flutter_codecheck@main
        with:
          flutter-version: ${{ needs.setup.outputs.flutter-version }}

      - name: Dry publish check
        run: cd packages/${{ inputs.package-name }} && flutter pub publish --dry-run
