name: Code Check on Checkout

on:
  workflow_call:
    inputs:
      needs-test-report:
        type: boolean
        default: false

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      file-changed: ${{ steps.filter.outputs.file-changed }}
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Get Flutter SDK version constraints and packages
        id: matrix
        uses: arxdeus/github_workflows/actions/flutter_parse_versions@main
  checkout:
    name: "Codecheck - ${{ strategy.job-index }}"
    needs: setup
    if: ${{ needs.setup.outputs.file-changed == 'true' || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
    timeout-minutes: 10
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: "Setup (Flutter ${{ matrix.flutter-version }})"
        uses: arxdeus/github_workflows/actions/flutter_setup@main
        with:
          flutter-version: ${{ matrix.flutter-version }}

      - name: Run tests parallel
        uses: sambacha/parallelish@v1.0.0
        id: testing-tasks
        with:
          cmd1: find packages/**/lib packages/**/test -name "*.dart" ! -name "*.*.dart" -print0 | xargs -0 dart format --set-exit-if-changed --line-length 120
          cmd2: flutter analyze --fatal-infos --fatal-warnings --no-pub
          cmd3: ls -d packages/* | xargs flutter test --file-reporter="json:${{ github.workspace }}/flutter-test-report.json" --concurrency=6 --no-pub --coverage

      - name: Write test report
        uses: dorny/test-reporter@v1
        # PRs from forks have no write permissions.
        if: github.event.pull_request.head.repo.fork == false && (success() || failure()) && (${{ inputs.needs-test-report }} == true)
        with:
          name: "Test Report (Flutter ${{ matrix.flutter-version }})"
          path: ${{ github.workspace }}/flutter-test-report.json
          reporter: flutter-json
