name: Code Check on Checkout

on:
  workflow_call:
    inputs:
      needs-test-report:
        type: boolean
        default: false

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      flutter-file-changed: ${{ steps.filter.outputs.flutter-file-changed }}
      flutter-matrix: ${{ steps.flutter-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Filter changed files
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            flutter-file-changed:
              - '**.dart'
              - 'pubspec.yaml'
              - 'pubspec.lock'

      - name: Get Flutter SDK version constraints and packages
        id: flutter-matrix
        # Extract the lower bound from pubspec.yaml and the upper bound from .fvmrc
        run: |
          {
            echo 'matrix<<EOF'
            jq -cn  --argjson flutter-version "[\"$(cat pubspec.yaml | yq .environment.flutter | grep -oP '(?<=\>=)[0-9]+\.[0-9]+\.[0-9]+' | head -1)\", \"$(cat .fvmrc | jq -r .flutter)\"]" --argjson package "[$(ls packages | sed "s/^/\"/;s/$/\"/" | tr "\n" "," | sed 's/.$//')]" '$ARGS.named'
            echo EOF
          } >> "$GITHUB_OUTPUT"
      - name: Print output values
        run: |
          echo "flutter-file-changed=${{ steps.filter.outputs.flutter-file-changed }}"
          echo "matrix=${{ steps.flutter-matrix.outputs.matrix }}"
  checkout:
    needs: setup
    if: ${{ needs.setup.outputs.flutter-file-changed == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.flutter-matrix) }}
    name: "Check code with analysis, format, and tests"
    timeout-minutes: 10
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      - name: "Codecheck (Package: ${{ needs.setup.outputs.package }}, Flutter ${{ matrix.flutter-version }})"
        uses: arxdeus/github_workflows/actions/flutter_codecheck@main
        with:
          working-directory: packages/${{ needs.setup.outputs.package }}
          flutter-version: ${{ needs.setup.outputs.flutter-version }}
      - name: Write test report
        uses: dorny/test-reporter@v1
        # PRs from forks have no write permissions.
        if: github.event.pull_request.head.repo.fork == false && (success() || failure()) && (${{ inputs.needs-test-report }} == true)
        with:
          name: Test Report (Flutter ${{ matrix.flutter-version }})
          path: ${{ github.workspace }}/flutter-test-report.json
          reporter: flutter-json
