name: Code Check on Checkout

on:
  workflow_call:
    inputs:
      needs-test-report:
        type: boolean
        default: false

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      flutter-file-changed: ${{ steps.filter.outputs.flutter-file-changed }}
      flutter-lower-bound: ${{ steps.flutter-version-constraint.outputs.lower-bound }}
      flutter-upper-bound: ${{ steps.flutter-version-constraint.outputs.upper-bound }}
    steps:
      - uses: actions/checkout@v4

      - name: Filter changed files
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            flutter-file-changed:
              - '**.dart'
              - 'pubspec.yaml'
              - 'pubspec.lock'

      - name: Get Flutter SDK version constraint
        id: flutter-version-constraint
        # Extract the lower bound from pubspec.yaml and the upper bound from .fvmrc
        run: |
          sdk_constraint=$(cat pubspec.yaml | yq .environment.flutter)
          lower_bound=$(echo "$sdk_constraint" | grep -oP '(?<=\>=)[0-9]+\.[0-9]+\.[0-9]+' | head -1)
          upper_bound=$(cat .fvmrc | jq -r .flutter)
          echo "lower-bound=$lower_bound" >> "$GITHUB_OUTPUT"
          echo "upper-bound=$upper_bound" >> "$GITHUB_OUTPUT"

      - name: Print output values
        run: |
          echo "flutter-file-changed=${{ steps.filter.outputs.flutter-file-changed }}"
  checkout:
    needs: setup
    if: ${{ needs.setup.outputs.flutter-file-changed == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flutter-version:
          - ${{ needs.setup.outputs.flutter-lower-bound }}
          - ${{ needs.setup.outputs.flutter-upper-bound }}
    name: "Check code with analysis, format, and tests"
    timeout-minutes: 10
    steps:
      - name: "Codecheck (Flutter ${{ matrix.flutter-version }})"
        uses: arxdeus/github_workflows/actions/flutter_codecheck@main
        with:
          flutter-version: ${{ needs.setup.outputs.flutter-version }}
      - name: Write test report
        uses: dorny/test-reporter@v1
        # PRs from forks have no write permissions.
        if: github.event.pull_request.head.repo.fork == false && (success() || failure()) && (${{ inputs.needs-test-report}} == true)
        with:
          name: Test Report (Flutter ${{ matrix.flutter-version }})
          path: ${{ github.workspace }}/flutter-test-report.json
          reporter: flutter-json
