name: Code Check

on:
  workflow_call:
    inputs:
      line-length:
        type: number
        default: 80
      needs-test-report:
        type: boolean
        default: false

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      file-changed: ${{ steps.matrix.outputs.file-changed }}
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Get Flutter SDK version constraints and packages
        id: matrix
        uses: arxdeus/github_workflows/actions/flutter_parse_versions@main
  checkout:
    name: "Codecheck - ${{ strategy.job-index }}"
    needs: setup
    if: |
      ${{ needs.setup.outputs.file-changed == 'true' }} ||
      contains(github.event.issue.labels.*.name, 'release')
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
    timeout-minutes: 10
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: "Setup (Flutter ${{ matrix.flutter-version }})"
        uses: arxdeus/github_workflows/actions/flutter_setup@main
        with:
          flutter-version: ${{ matrix.flutter-version }}

      - name: Run tests parallel
        uses: arxdeus/parallel@v2
        with:
          commands: |
            - directory: pwd && ls
            - format: find packages -type f -name *.dart ! -name *.*.dart -print0 | xargs -0 dart format --set-exit-if-changed --line-length ${{ inputs.line-length }}
            - analyze: flutter analyze --fatal-infos --fatal-warnings --no-pub
            - tests: find packages -maxdepth 1 -type d | tail -n+2 | xargs flutter test --file-reporter="json:${{ github.workspace }}/flutter-test-report.json" --concurrency=6 --no-pub --coverage

      - name: Write test report
        uses: dorny/test-reporter@v1
        # PRs from forks have no write permissions.
        if: github.event.pull_request.head.repo.fork == false && (success() || failure()) && (${{ inputs.needs-test-report }} == true)
        with:
          name: "Test Report (Flutter ${{ matrix.flutter-version }})"
          path: ${{ github.workspace }}/flutter-test-report.json
          reporter: flutter-json
